### ISSUE TITLE
Helm deploy example causes initialization to fail

### ISSUE THREAD

**Issue by TomyLobo** [siderolabs/talos-cloud-controller-manager#218]
### Description

The installation documentation contains an override for `tolerations`:
https://github.com/siderolabs/talos-cloud-controller-manager/blob/main/charts/talos-cloud-controller-manager/README.md#deploy-example
This causes initialization to fail, because the relevant pods cannot be scheduled.

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by sergelogvinov** [comment]
fixed #220
