### ISSUE TITLE
Missing Metadata on nodes prevent bootstraping

### ISSUE THREAD

**Issue by tei0h** [siderolabs/talos-cloud-controller-manager#77]
## Bug Report
When using the no cloud talos image to deploy talos on various resources (BareMetal and openstack), the talos ccm fail to get the needed metadata to complete the bootstrap process

### Description
I'm using the talos no cloud image to deploy talos to various platforms (openstack, baremetal and proxmox). When bootstrapping baremetal and OpenStack ressources, the bootstrap fails because Talos didn't generate the needed Metadata by talos CCM.  
The nodes in question are still stuck with the taint : node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule

### Logs
From CCM : 
```
I0817 13:01:02.886637       1 node_controller.go:263] Update 8 nodes status took 10.228623ms.
I0817 13:02:19.371544       1 node_controller.go:427] Initializing node talos-staging-wn-04 with cloud provider
E0817 13:02:19.377186       1 node_controller.go:236] error syncing 'talos-staging-wn-04': failed to get instance metadata for node talos-staging-wn-04: error getting metadata from the node talos-staging-wn-04: rpc error: code = NotFound desc = resource PlatformMetadatas.talos.dev(runtime/platformmetadata@undefined) doesn't exist, requeuing
I0817 13:02:39.334546       1 node_controller.go:427] Initializing node talos-staging-cp-03 with cloud provider
E0817 13:02:39.337182       1 node_controller.go:236] error syncing 'talos-staging-cp-03': failed to get instance metadata for node talos-staging-cp-03: error getting metadata from the node talos-staging-cp-03: rpc error: code = NotFound desc = resource PlatformMetadatas.talos.dev(runtime/platformmetadata@undefined) doesn't exist, requeuing
```

When running "talosctl -n $IP get platformmetadatas.talos.dev" from a working (proxmox) node i do have some metadatas : 
`NODE          NAMESPACE   TYPE               ID                 VERSION   PLATFORM   TYPE   REGION   ZONE
172.16.10.1   runtime     PlatformMetadata   platformmetadata   1         nocloud`

And on a non working node (baremetal/  i have an empty return

### Environment

- Talos CCM version: 1.4.0
- Talos version: 1.5.0 or 1.4.5
- Kubernetes version: v1.27.3
- CNI: Cilium without KubeProxy
- Platform: amd64 on baremetal/openstack

**Comment by sergelogvinov** [comment]
Hello, the bast way to understand what wrong happened:
1. check the Talos PlatformMetadata resource ```talosctl -n $IP get platformmetadatas.talos.dev -oyaml```, (`-oyaml` is required). By this command you will see that Talos figured out about current planform. 
2. check the dmesg logs (first 150 line should enough) 

```
resource PlatformMetadatas.talos.dev(runtime/platformmetadata@undefined) doesn't exist, requeuing
```
i think, Talos cannot call the metadata server (no route to host) or have issue with parsing the response.
