### ISSUE TITLE
Image tag incorrect when deploying through helm

### ISSUE THREAD

**Issue by kanya-approve** [siderolabs/talos-cloud-controller-manager#96]
### Description

Latest version of the OCI chart (0.2.1) tries to pull the image "ghcr.io/siderolabs/talos-cloud-controller-manager:1.4.0" which doesn't exist. I've resolved it by changing "image.tag" to "v1.4.0".

### Environment

- Talos CCM version: 1.4.0
- Talos version: 1.5.3
- Kubernetes version: 1.27.6
- Platform: linux arm64

**Comment by sergelogvinov** [comment]
Thank you for feedback.

We will fix it soon.
